In [1]:
import pandas as pd
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\\Users\\User\\OneDrive\\Desktop\\python\\Housing.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\OneDrive\\Desktop\\python\\Housing.csv'

In [ ]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [ ]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [ ]:
df.head(1)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished

In [ ]:
df=df.drop(['mainroad','guestroom','basement','hotwaterheating','airconditioning','furnishingstatus','prefarea'],axis=1    )

In [ ]:
df

        price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [ ]:
#faetures and target variable
X=df.drop(['price'],axis=1)

In [ ]:
#for target variable
y=df['price']

In [ ]:
#train test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train

     area  bedrooms  bathrooms  stories  parking
46   6000         3          2        4        1
93   7200         3          2        1        3
335  3816         2          1        1        2
412  2610         3          1        2        0
471  3750         3          1        2        0
..    ...       ...        ...      ...      ...
71   6000         4          2        4        0
106  5450         4          2        1        0
270  4500         3          2        3        1
435  4040         2          1        1        0
102  5500         3          2        4        1

[436 rows x 5 columns]

In [ ]:
y_train

46     7525000
93     6300000
335    3920000
412    3430000
471    3010000
        ...
71     6755000
106    6160000
270    4340000
435    3290000
102    6195000
Name: price, Length: 436, dtype: int64

In [ ]:
#scaling the data
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
#svr model
model=SVR(
    kernel='linear',
    gamma='scale',
    )

In [ ]:
model.fit(X_train,y_train)

SVR()

In [ ]:
#predictions
y_pred=model.predict(X_test)

In [ ]:
y_pred

array([4291030.24435396, 4291024.79071864, 4290935.38648078,
       4290962.44930117, 4290944.98176684, 4290977.98903694,
       4291018.39490216, 4291014.88261073, 4290945.35746905,
       4290940.76642675, 4291011.16445676, 4290934.82822975,
       4290933.90574826, 4290946.81991129, 4290951.8446412 ,
       4291008.46911505, 4290944.48366682, 4290991.28270166,
       4290989.40066307, 4290955.47232556, 4291007.04338139,
       4290979.44042896, 4290933.66115289, 4290966.86572708,
       4291014.1570587 , 4291025.97510416, 4290932.82591084,
       4290991.66653473, 4291014.49645197, 4290942.25196708,
       4290997.89414023, 4290962.54868365, 4291022.68490971,
       4290983.90513464, 4290983.11904198, 4291013.69645908,
       4290997.69742149, 4290973.30417831, 4290942.27162115,
       4291001.71837571, 4291016.15781954, 4290933.60094565,
       4291024.4911432 , 4290970.35074313, 4290965.97902478,
       4290966.46754761, 4291024.40945041, 4290995.00463102,
       4290983.5962892 , 4290973.91519937, 4291026.36961141,
       4290945.12938449, 4290990.33388496, 4290956.77758547,
       4290975.37610962, 4290940.81262622, 4291029.5403053 ,
       4290945.89093826, 4290997.66994269, 4290934.21822516,
       4290996.23395641, 4290988.27232331, 4291002.82256901,
       4290942.81272569, 4291003.23883833, 4290991.68404647,
       4291015.42175172, 4290946.51378096, 4291011.90000092,
       4291000.34373524, 4290990.93174055, 4290999.46113091,
       4290997.11046351, 4291021.82815405, 4290945.31149455,
       4291010.22430831, 4290990.93106567, 4290941.3609219 ,
       4290983.3425562 , 4290958.54776192, 4291031.21043938,
       4290993.69391719, 4291016.0846782 , 4291001.92519639,
       4290947.69481758, 4291016.04432882, 4290940.75561767,
       4290964.37389354, 4291031.72880794, 4291015.09077728,
       4290992.41264693, 4291007.22959456, 4290948.35332771,
       4290948.13315217, 4291009.52647097, 4290975.69764394,
       4291011.1322361 , 4291023.94829981, 4291003.06318273,
       4291016.56391241, 4290988.91809463, 4291019.23314235,
       4290974.70606465, 4291007.75379365, 4291015.82746207,
       4291013.29602017, 4291028.90261227, 4291024.18277693,
       4291018.6415596 ])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test,y_pred)
print("mean_squared_error", mse)
r2 = r2_score(y_test,y_pred)
print("r2_score",r2)

mean_squared_error 5567921966485.061
r2_score -0.10156189252588588